site_name: ShowcaseMe Templates
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: light blue

nav:
  -  Getting Stared: "index.md"
  -  HTML Structure: "html.md"
  -  Portfolio: "portfolio.md"
  -  Others: "css.md"
  -  Credits: "credits.md"
  -  Changelog: "changelog.md"
  -  Help: "help.md"
